insert into ac_state values(35,'Andaman and Nicobar Islands','AN');
insert into ac_state values(37,'Andhra Pradesh','AP');
insert into ac_state values(12,'Arunachal Pradesh','AR');
insert into ac_state values(18,'Assam','AS');
insert into ac_state values(10,'Bihar','BR');
insert into ac_state values(4,'Chandigarh','CH');
insert into ac_state values(22,'Chattisgarh','CG');
insert into ac_state values(26,'Dadra and Nagar Haveli','DN');
insert into ac_state values(25,'Daman and Diu','DD');
insert into ac_state values(7,'Delhi','DL');
insert into ac_state values(30,'Goa','GA');
insert into ac_state values(24,'Gujarat','GJ');
insert into ac_state values(6,'Haryana','HR');
insert into ac_state values(2,'Himachal Pradesh','HP');
insert into ac_state values(1,'Jammu and Kashmir','JK');
insert into ac_state values(20,'Jharkhand','JH');
insert into ac_state values(29,'Karnataka','KA');
insert into ac_state values(32,'Kerala','KL');
insert into ac_state values(38,'Ladakh','LA');
insert into ac_state values(31,'Lakshadweep','LD');
insert into ac_state values(23,'Madhya Pradesh','MP');
insert into ac_state values(27,'Maharashtra','MH');
insert into ac_state values(14,'Manipur','MN');
insert into ac_state values(17,'Meghalaya','ML');
insert into ac_state values(15,'Mizoram','MZ');
insert into ac_state values(13,'Nagaland','NL');
insert into ac_state values(21,'Odisha','OR');
insert into ac_state values(34,'Puducherry','PY');
insert into ac_state values(3,'Punjab','PB');
insert into ac_state values(8,'Rajasthan','RJ');
insert into ac_state values(11,'Sikkim','SK');
insert into ac_state values(33,'Tamil Nadu','TN');
insert into ac_state values(36,'Telangana','TS');
insert into ac_state values(16,'Tripura','TR');
insert into ac_state values(9,'Uttar Pradesh','UP');
insert into ac_state values(5,'Uttarakhand','UA');
insert into ac_state values(19,'West Bengal','WB');


